version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registration
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - registration-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "registration" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  # Spring Boot
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - registration-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/registration
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

networks:
  registration-network:
    driver: bridge

volumes:
  db_data:
